language: python
python:
- 3.7
before_install: pip install --upgrade pip setuptools wheel
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sagar87
  password:
    secure: EsyY6LiZLJtx0MJNLFLAo7cVlh2EOZx29X18fpZaVGbTOiNHsKsNvcqN5SgGv5TdEi9TYupTeP4833by8S1rGIhjRtVG3qcoFfJUx2dFvp/X9Gb42qsFa6AhooH5O0zHrCTZmxTsJr8InZj4xFD4ngbW3ItXhiIdDcDCfDJSf/AMtYnAvcYBEbkwh6VuuoVuhcBz2SjY0iAmPA60qcPPO0186LOskNhR09prBAjYqHChbIysiQS9Ksm29tNtOd6j6l2J69EGuj6RQHh9EdZDevOOEjBgXdA5o2EUdatHJPXkukINgn28+8qYvGvV7kTSfDu+RqGB0gW3uwuywbLqO2ISNmtVxbCqz3LIkTSjhuxDN/ht969jL27Kx7+sBGMflQvkbQpHqrju8i6GX+k7/FKlDhodL3h0HeS+wJmwUV3i9cyh5IuSg+ExtG3wjXBy0tzeAVFlKtV8AOhsfLaNcJXFZkpQQBhWx/99Kbx5qCB3uduxeGb8eLQa8K1MPE7ylkVebMutPp2hBqsHgsRmppYdZoOHUkCid1hlhCYP4JsOjgy0sphlYYBWkkAq1qhBywvQ+i2CoN8wZ4d07kZZaKTi3QFEgEV59bdxQfvsUjXapvqiWChHfP/iWcgCdgi3W019GVEzRuUGnOLMhMpPK2Mv+U2SLjzP6/C84qjWbEs=
  on:
    tags: true
    repo: sagar87/tensorsignatures
    python: 3.7
